datasets:
  skin_align:
    data_type: images
    build_info:
      storage: /ibex/ai/project/c2032/skingpt/SkinGPT-4/dataset/skin_dataset_v2/skin_align
      #storage: /home/zhouj0d/Science/PID27.ChatSkin/skin_dataset_v2/skin_align
      #storage: /home/juexiao_zhou/disk/SkinGPT-4/dataset/skin_dataset_v2/skin_align
