model:
  arch: skin_gpt4

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  freeze_qformer: True

  # Q-Former
  num_query_token: 32

  # Vicuna
  llm_model: "/ibex/ai/project/c2032/skingpt/SkinGPT-4/weights/bloom-7b1"
  #llm_model: "/home/zhouj0d/disk4/PID27.ChatSkin/SkinGPT-4/weights/bloom-7b1"

  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
